theme: jekyll-theme-minimal
title: "GPSconverter (Global-Positioning-System Converter)"
email: sammarcocarmelo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Python application to manipulate & view GPS data
logo: "GPSconverter/DATA/LOGOproj.png"
show_downloads: true
