"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GPSconverter.py']
APP_NAME = "GPSconverter"
DATA_FILES = ['assets/LOGO.gif']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': '/Users/carmelosammarco/Desktop/GPSconverter/pyinstaller/assets/FILE.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "GPS data converter-visualizer",
        'CFBundleIdentifier': "com.carmelosammarco.osx.GPSconverter",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2021, Carmelo Sammarco, All Rights Reserved"
    }
}
           

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
